[tool.poetry]
name = "iamages_server"
version = "4.0.0"
description = "Server for the Iamages service."
authors = ["Nam Thành Nguyễn <35841468+jkelol111@users.noreply.github.com>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
passlib = {extras = ["argon2", "bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.9"
Jinja2 = "^3.1.2"
python-magic = "^0.4.27"
brotli-asgi = "^1.4.0"
orjson = "^3.9.10"
uvicorn = "^0.20.0"
Pillow = "^10.1.0"
pymongo = "^4.6.0"
python-jose = {extras = ["pycryptodome"], version = "^3.3.0"}
tqdm = "^4.66.1"
pydantic = {extras = ["email"], version = "^2.5.1"}
gunicorn = "^21.2.0"
python-dotenv = "^1.0.0"
setuptools = "^68.2.2"
pydantic-settings = "^2.1.0"
pydantic-mongo = "^2.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
